<?php
session_start();
include "../../global_paths.php";
require_once('../tcpdf/config/lang/eng.php');
require_once('../tcpdf/tcpdf.php');
$doc_root = $_SERVER['DOCUMENT_ROOT'];
require_once $doc_root.'/business_logic/admin/db/db_manager.php';

$project = $_SESSION['project'];
$sub_project = $_SESSION['sub_project'];
$fullname = $_SESSION['fullname'];
$timestamp = date("Y-m-d H:i:s");

$type_flag= $_POST['type_flag'];

$cust_name=$_POST['cust_name'];
$cust_notes=$_POST['cust_notes'];
$cust_address=$_POST['cust_address'];
$cust_city=$_POST['cust_city'];
$cust_job=$_POST['cust_job'];
$cust_email=$_POST['cust_email'];
$cust_cell_phone=$_POST['cust_cell_phone'];
$cust_home_phone=$_POST['cust_home_phone'];
$cust_salesperson=$_POST['cust_salesperson'];
$cust_referred_by=$_POST['cust_referred_by'];
$cust_appointment_date=$_POST['cust_appointment_date'];
$cust_appointment_time=$_POST['cust_appointment_time'];
$cust_quote=$_POST['cust_quote'];
$cust_instruction=$_POST['cust_instruction'];
$cust_complaint=$_POST['cust_complaint'];

ob_start();
include($doc_root.'/business_logic/admin/pdf_html_template.php');
$html = ob_get_contents();
ob_end_clean();

// Extend the TCPDF class to create custom Header and Footer

class MYPDF extends TCPDF {
    //Page header
    public function Header() {
        // get the current page break margin
        $bMargin = $this->getBreakMargin();
        // get current auto-page-break mode
        $auto_page_break = $this->AutoPageBreak;
        // disable auto-page-break
        $this->SetAutoPageBreak(false, 0);
		$img_file = '../../images/pdf_background_template_1.png';
        //$this->Image($img_file, 0, 0, 210, 297, '', '', '', false, 300, '', false, false, 0);
        // restore auto-page-break status
        $this->SetAutoPageBreak($auto_page_break, $bMargin);
        // set the starting point for the page content
        $this->setPageMark();
    }
}

// create new PDF document
$pdf = new MYPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

// create new PDF document
//$pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

// set document information
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('http://www.arbco.us/');
$pdf->SetTitle('Arbco: CSR Scripting System');
$pdf->SetSubject($project . ': ' . $sub_project);
$pdf->SetKeywords($project . ', ' . $sub_project . 'Arbco, CSR Scripting System');

// set header and footer fonts
$pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
$pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));

// set default monospaced font
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

//set margins
$pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
$pdf->setPrintHeader(false);
$pdf->setPrintFooter(false);

//set auto page breaks
$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

//set image scale factor
$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

//set some language-dependent strings
$pdf->setLanguageArray($l);

// set default font subsetting mode
$pdf->setFontSubsetting(true);
$pdf->SetFont('dejavusans', '', 12, '', true);

$pdf->setPrintHeader(true);

//$pdf->setJPEGQuality(100);
//$pdf->Image('../../images/pdf_background_template_1.png', 0, 34, 750, 1020, 'PNG', '', 'T', false, 300, '', false, false, 0, false, false, true);

$pdf->setPrintHeader(true);
$pdf->AddPage();
$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);

$pdf->setPrintFooter(true);
$pdf->writeHTMLCell($w=0, $h=0, $x='', $y='', $html, $border=0, $ln=1, $fill=0, $reseth=true, $align='', $autopadding=true);

$user_filename = 'csr_scripts/csr_autogenerated_pdfs/order_pdf_' . $fullname . '.pdf';
$pdf->Output($user_filename, 'F');

	
echo $user_filename;
?>